# Generated by Django 5.1.5 on 2025-02-14 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ashaworker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='logintable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='panchayath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('desc', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('foodname', models.CharField(max_length=100)),
                ('quantity', models.BigIntegerField()),
                ('ashaworkerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ashaworker')),
            ],
        ),
        migrations.CreateModel(
            name='expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('gender', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable')),
            ],
        ),
        migrations.AddField(
            model_name='ashaworker',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable'),
        ),
        migrations.CreateModel(
            name='mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='foodallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=100)),
                ('FOOD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.food')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mother')),
            ],
        ),
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('age', models.BigIntegerField()),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mother')),
            ],
        ),
        migrations.CreateModel(
            name='reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.BigIntegerField()),
                ('desc', models.CharField(max_length=10)),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mother')),
            ],
        ),
        migrations.CreateModel(
            name='shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.expert')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mother')),
                ('SHEDULE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shedule')),
            ],
        ),
        migrations.CreateModel(
            name='childvaccinationdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('CHILDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.child')),
                ('VACCINATIONID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vaccination')),
            ],
        ),
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardnumder', models.BigIntegerField()),
                ('PANCHAYATH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.panchayath')),
            ],
        ),
        migrations.AddField(
            model_name='ashaworker',
            name='WARD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ward'),
        ),
    ]
