# Generated by Django 5.1.5 on 2025-04-08 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_reminder_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='SHEDULE',
        ),
        migrations.AddField(
            model_name='prescription',
            name='BOOKING',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking'),
            preserve_default=False,
        ),
    ]
