# Generated by Django 5.1.5 on 2025-04-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_prescription_shedule_prescription_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='WARD',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='myapp.ward'),
            preserve_default=False,
        ),
    ]
