# Generated by Django 5.1.5 on 2025-04-24 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_mother_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='ashaworkerid',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='myapp.ashaworker'),
            preserve_default=False,
        ),
    ]
